eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ #服务注册中心
server:
  port: 8764
spring:
  application:
    name: service-ribbon
  #cloud:
    #config:
      #label: master
      #profile: dev
      #uri: http://localhost:8888/   #SpringCloud Config 从git拿配置,仓库服务器
  zipkin:
    base-url: http://localhost:9411 #设置链路跟踪服务器   